version: "3.8"
services:
  sender:
    build:
      context: ./
      dockerfile: Dockerfile_send
  recevier:
    build:
      context: ./
      dockerfile: Dockerfile_receive
  rabbitmq:
    image: rabbitmq:3.8.9-management
    container_name: kanino
    environment:
      RABBITMQ_ERLANG_COOKIE: "SECRET"
      RABBITMQ_DEFAULT_USER: "kanin"
      RABBITMQ_DEFAULT_PASS: "kanin"
    ports:
      - 5672:5672
      - 15672:15672
